// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfNujZpLHx2Jr9oNCHfTSIHIYj5KjZk7k',
    appId: '1:161404762435:web:a3a33e9057efc82ddb17f6',
    messagingSenderId: '161404762435',
    projectId: 'lg-cleteci-cross-platform-test',
    authDomain: 'lg-cleteci-cross-platform-test.firebaseapp.com',
    storageBucket: 'lg-cleteci-cross-platform-test.firebasestorage.app',
    measurementId: 'G-VYG1JTQMVJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoanO2gzDA8S0Yfr2p4xaxSb1av5g6ZVc',
    appId: '1:161404762435:android:d856aa6590aba107db17f6',
    messagingSenderId: '161404762435',
    projectId: 'lg-cleteci-cross-platform-test',
    storageBucket: 'lg-cleteci-cross-platform-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATnO1kfqlrzfS6yCeHtCu4hniBxXtAzJY',
    appId: '1:161404762435:ios:6ddd108df8135e41db17f6',
    messagingSenderId: '161404762435',
    projectId: 'lg-cleteci-cross-platform-test',
    storageBucket: 'lg-cleteci-cross-platform-test.firebasestorage.app',
    iosBundleId: 'com.example.cleteciCrossPlatform',
  );

}