// Mocks generated by Mockito 5.4.6 from annotations
// in cleteci_cross_platform/test/ui/common/widgets/default_app_bar_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i5;

import 'package:cleteci_cross_platform/ui/auth/view_model/local_auth_state.dart'
    as _i3;
import 'package:local_auth/local_auth.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeLocalAuthentication_0 extends _i1.SmartFake
    implements _i2.LocalAuthentication {
  _FakeLocalAuthentication_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LocalAuthState].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalAuthState extends _i1.Mock implements _i3.LocalAuthState {
  MockLocalAuthState() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LocalAuthentication get auth =>
      (super.noSuchMethod(
            Invocation.getter(#auth),
            returnValue: _FakeLocalAuthentication_0(
              this,
              Invocation.getter(#auth),
            ),
          )
          as _i2.LocalAuthentication);

  @override
  bool get isAuthenticating =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticating),
            returnValue: false,
          )
          as bool);

  @override
  _i3.LocalAuthSupportState get supportState =>
      (super.noSuchMethod(
            Invocation.getter(#supportState),
            returnValue: _i3.LocalAuthSupportState.unknown,
          )
          as _i3.LocalAuthSupportState);

  @override
  bool get canCheckBiometrics =>
      (super.noSuchMethod(
            Invocation.getter(#canCheckBiometrics),
            returnValue: false,
          )
          as bool);

  @override
  List<_i2.BiometricType> get availableBiometrics =>
      (super.noSuchMethod(
            Invocation.getter(#availableBiometrics),
            returnValue: <_i2.BiometricType>[],
          )
          as List<_i2.BiometricType>);

  @override
  _i3.LocalAuthStateValue get authorized =>
      (super.noSuchMethod(
            Invocation.getter(#authorized),
            returnValue: _i3.LocalAuthStateValue.authorized,
          )
          as _i3.LocalAuthStateValue);

  @override
  set isAuthenticating(bool? value) => super.noSuchMethod(
    Invocation.setter(#isAuthenticating, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i4.Future<void> checkBiometrics() =>
      (super.noSuchMethod(
            Invocation.method(#checkBiometrics, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> getAvailableBiometrics() =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableBiometrics, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> authenticate() =>
      (super.noSuchMethod(
            Invocation.method(#authenticate, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> authenticateWithBiometrics() =>
      (super.noSuchMethod(
            Invocation.method(#authenticateWithBiometrics, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> cancelAuthentication() =>
      (super.noSuchMethod(
            Invocation.method(#cancelAuthentication, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
