name: CI

on:
  push:
    branches: [ main, master, develop, features ]
  pull_request:
    branches: [ main, master, develop, features ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
    - run: flutter pub get
    - run: echo "${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}" > .env
    - run: flutter test --coverage
    - run: flutter build web
    - name: Setup LCOV
      uses: hrishikesh-kadam/setup-lcov@v1
    # - name: Report Code Coverage
    #   uses: zgosalvez/github-actions-report-lcov@v3
    #   with:
    #     coverage-files: coverage/lcov.info
    #     minimum-coverage: 80
    #     artifact-name: code-coverage-report
    #     github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage/lcov.info
        fail_ci_if_error: false
    - name: Check 80% Coverage Minimum (Alternativa)
      run: |
        coverage_percent=$(awk '/^overall coverage:/ {print $3}' coverage/lcov.info | sed 's/[^0-9.]//g')
        if (( $(echo "$coverage_percent < 80.0" | bc -l) )); then
          echo "❌ ERROR: La cobertura de código es del $coverage_percent%, y se requiere un 80%."
          exit 1
        else
          echo "✅ Cobertura OK: $coverage_percent%"
        fi
      shell: bash # Asegúrate de usar bash
  e2e-test:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'
    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
    - run: flutter pub get
    - run: flutter build web --release --pwa-strategy none
    - name: Start Flutter web server
      run: |
        flutter pub global activate dhttpd
        flutter pub global run dhttpd --path build/web --port 8080 &
        sleep 5
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    - name: Install Cypress dependencies
      run: npm install
    - name: Run E2E tests
      run: npm run test:e2e
    - name: Upload E2E test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: e2e-test-results
        path: |
          cypress/videos/
          cypress/screenshots/
  build-docker:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'
    steps:
    - uses: actions/checkout@v4
    - name: Build Docker image
      run: docker build -t cleteci-cross-platform .
    # Uncomment the following steps to push to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push to Docker Hub
      run: |
        docker tag cleteci-cross-platform ${{ secrets.DOCKER_USERNAME }}/cleteci-cross-platform:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/cleteci-cross-platform:latest
