name: Despliegue de Documentación a GitHub Pages (MkDocs)

on:
  push:
    branches:
      - develop
    paths:
      - 'docs/**'
      - 'mkdocs.yml' 

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Checkout del código del repositorio
      - name: Checkout del repositorio
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Paso 2: Configurar Python (MkDocs requiere Python)
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Paso 3: Instalar MkDocs y el tema Material
      - name: Instalar MkDocs y dependencias
        run: |
          pip install mkdocs mkdocs-material

      # Paso 4: Construir el sitio estático
      # MkDocs compila los archivos .md y genera el sitio estático en la carpeta 'site'
      - name: Construir el sitio de documentación
        run: mkdocs build

      # Paso 5: Configurar GitHub Pages
      # Inicializa el entorno de despliegue de Pages (necesario para la acción final)
      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      # Paso 6: Cargar el artefacto de la documentación
      # Sube el contenido de la carpeta 'site' a GitHub, listo para ser desplegado
      - name: Subir artefacto de GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'site' # MkDocs siempre genera la salida en la carpeta 'site'

  # Job de Despliegue: Se ejecuta una vez que el artefacto ha sido creado
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} # URL de despliegue
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Paso 7: Desplegar el artefacto a GitHub Pages
      # Esta es la acción final que publica el sitio en la URL de GitHub Pages
      - name: Desplegar a GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4