// Mocks generated by Mockito 5.4.6 from annotations
// in cleteci_cross_platform/test/ui/speech_to_text/speech_to_text_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:cleteci_cross_platform/services/speech_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:speech_to_text/speech_to_text.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [SpeechService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSpeechService extends _i1.Mock implements _i2.SpeechService {
  MockSpeechService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isListening =>
      (super.noSuchMethod(Invocation.getter(#isListening), returnValue: false)
          as bool);

  @override
  _i3.Future<bool> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> isAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isAvailable, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> startListening({
    required dynamic Function(String)? onResult,
    required dynamic Function(double)? onSoundLevelChange,
    required dynamic Function()? onListeningStarted,
    required dynamic Function()? onListeningStopped,
    String? localeId,
    int? listenFor,
    int? pauseFor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#startListening, [], {
              #onResult: onResult,
              #onSoundLevelChange: onSoundLevelChange,
              #onListeningStarted: onListeningStarted,
              #onListeningStopped: onListeningStopped,
              #localeId: localeId,
              #listenFor: listenFor,
              #pauseFor: pauseFor,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> stopListening() =>
      (super.noSuchMethod(
            Invocation.method(#stopListening, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> cancelListening() =>
      (super.noSuchMethod(
            Invocation.method(#cancelListening, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.LocaleName>> getLocales() =>
      (super.noSuchMethod(
            Invocation.method(#getLocales, []),
            returnValue: _i3.Future<List<_i4.LocaleName>>.value(
              <_i4.LocaleName>[],
            ),
          )
          as _i3.Future<List<_i4.LocaleName>>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
